### ISSUE TITLE
Wrong font

### ISSUE THREAD

**Issue by just-a-hriday** [GianniLab/Mailspring-11-Dark#1]
The screenshot shows a clean sans-serif font - but it's some kind of serif font on my app.

**Comment by just-a-hriday** [comment]
`index.less` seems to use a "Google Sans". What font is that?

**Comment by GianniLab** [comment]
Hi @Mr-Anonymous75, in the link below, you will find a short info about Google sans
[https://www.xda-developers.com/google-sans-font-chrome-os/](https://www.xda-developers.com/google-sans-font-chrome-os/)
You can comment or delete the custom font family or replace it with one of your liking that you have installed on your machine

**Comment by just-a-hriday** [comment]
Thanks! I wasn't really expecting a response - especially this soon.

It seems like Google Sans is only available on ChromeOS. Is there any way I can get it on Windows, or will I have to change the font?

**Comment by GianniLab** [comment]
Hi! You are welcome!

For Google Sans you can find it here [https://github.com/sahibjotsaggu/Google-Sans-Fonts](url)
You have several options:
- you can comment / delete the custom font family or replace it in index.less with a font of your liking that you have installed on your machine
- or re-download and update the theme, after your report I proceeded to add the "system font" as an alternative to google sans

**Comment by just-a-hriday** [comment]
> Hi! You are welcome!
> 
> For Google Sans you can find it here [https://github.com/sahibjotsaggu/Google-Sans-Fonts](url) You have several options:
> 
> * you can comment / delete the custom font family or replace it in index.less with a font of your liking that you have installed on your machine
> * or re-download and update the theme, after your report I proceeded to add the "system font" as an alternative to google sans

Thanks for your help! I installed Google Sans and now the theme works perfectly.
